# Generated by Django 5.2.5 on 2026-08-05 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0015_alter_appnotification_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resignation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_on", models.DateTimeField(auto_now_add=True)),
                ("notice_period_days", models.PositiveIntegerField(default=30)),
                ("proposed_last_working_day", models.DateField()),
                ("approved_last_working_day", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("acknowledged", "Acknowledged"),
                            ("withdrawn", "Withdrawn"),
                            ("completed", "Completed"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resignation",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resignation",
                "verbose_name_plural": "Resignations",
                "db_table": "exit_management_resignation",
                "ordering": ["-submitted_on"],
            },
        ),
        migrations.CreateModel(
            name="ExitInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conducted_on", models.DateField(blank=True, null=True)),
                ("reason_for_leaving", models.TextField()),
                (
                    "satisfaction_score",
                    models.IntegerField(blank=True, help_text="Score 1-5", null=True),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "conducted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_exit_interviews",
                        to="users.employee",
                    ),
                ),
                (
                    "resignation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exit_interview",
                        to="exit_management.resignation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exit Interview",
                "verbose_name_plural": "Exit Interviews",
                "db_table": "exit_management_exitinterview",
            },
        ),
        migrations.CreateModel(
            name="ClearanceChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("Finance", "Finance"),
                            ("Admin", "Admin"),
                            ("HR", "HR"),
                        ],
                        default="IT",
                        max_length=20,
                    ),
                ),
                ("item_description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("done", "Done")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("remark", models.TextField(blank=True)),
                ("cleared_on", models.DateTimeField(blank=True, null=True)),
                (
                    "cleared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cleared_exit_items",
                        to="users.employee",
                    ),
                ),
                (
                    "resignation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clearance_items",
                        to="exit_management.resignation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clearance Checklist Item",
                "verbose_name_plural": "Clearance Checklist Items",
                "db_table": "exit_management_clearancechecklistitem",
            },
        ),
    ]
