# Generated by Django 5.2.5 on 2026-08-13 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exit_management", "0001_initial"),
        ("users", "0016_employee_aadhaar_number_employee_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resignation",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resignations",
                to="users.employee",
            ),
        ),
    ]
