"""
Django settings for attendance_backend project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rlv)j$g+ic#&43$4c7jy$)ax!p&n=e*%jnn2xqlrr2-ldigxwl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (os.getenv("DEBUG", "false").strip().lower() in ["1", "true", "yes", "y"])

_allowed_hosts = (os.getenv("ALLOWED_HOSTS", "") or "").strip()
if _allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]
else:
    ALLOWED_HOSTS = [
        'localhost',
        '127.0.0.1',
        'attend-api.vibetechlabs.cloud',
        'attend.vibetechlabs.cloud',
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'leaves',
    'users',
    'updates',
    'attendance',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'attendance_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'attendance_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'attendance_db',
        'USER': 'attendance_user',   
        'PASSWORD': 'Attendance@123', 
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
}

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

_default_cors_origins = {
    "https://attend.vibetechlabs.cloud",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
}
_cors_allowed = (os.getenv("CORS_ALLOWED_ORIGINS", "") or "").strip()
if _cors_allowed:
    _env_cors_origins = {h.strip() for h in _cors_allowed.split(",") if h.strip()}
    CORS_ALLOWED_ORIGINS = sorted(_default_cors_origins.union(_env_cors_origins))
else:
    CORS_ALLOWED_ORIGINS = sorted(_default_cors_origins)

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# AUTH_USER_MODEL = 'core.User'

AUTH_USER_MODEL = 'users.User'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Web Push (VAPID) config
WEB_PUSH_PUBLIC_KEY = os.getenv(
    "WEB_PUSH_PUBLIC_KEY",
    "BIEydom3zgcG71HGJAtl4HFDuwjEZnC_YOQ1GEIRV74_7g0iUFWLcM6JZ9HN7JLb7a-bFdpzPyraYzXAIr8ucZU",
)
WEB_PUSH_PRIVATE_KEY = os.getenv(
    "WEB_PUSH_PRIVATE_KEY",
    str(BASE_DIR / "vapid_private.pem"),
)
WEB_PUSH_SUBJECT = os.getenv("WEB_PUSH_SUBJECT", "mailto:admin@vtl.local")

# Face verification (dlib / face_recognition 128-D embeddings).
# Lower = stricter (fewer false matches). Typical same-person distances are often < 0.45.
FACE_MATCH_THRESHOLD = float(os.getenv("FACE_MATCH_THRESHOLD", "0.42"))

# Only when DEBUG is enabled: allow skipping geo + face checks for local testing,
# and allow many check-in / check-out cycles the same day (auto-closes any open session).
# In production (DEBUG=false) this is always false, even if the env var is set.
_debug_env = os.getenv("DEBUG", "false").strip().lower() in ["1", "true", "yes", "y"]
ATTENDANCE_RELAXED_VERIFY = _debug_env and os.getenv(
    "ATTENDANCE_RELAXED_VERIFY", ""
).strip().lower() in ["1", "true", "yes", "y"]