import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { History, Eye, User, FileText, Download, Printer } from "lucide-react";
import { fetchGeneratedLetters } from "@/api/documents";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { EmptyState } from "@/components/EmptyState";
import { MncLetterDocument } from "@/components/documents/MncLetterDocument";

export default function LetterHistory() {
  const [selectedLetter, setSelectedLetter] = useState<any | null>(null);

  const { data, isLoading, error } = useQuery({
    queryKey: ["generated-letters"],
    queryFn: () => fetchGeneratedLetters().then((res) => res.data),
  });

  const letters = Array.isArray(data) ? data : data?.results || [];

  const getDateDisplay = (item: any) => {
    const rawDate = item.generated_on || item.created_at;
    if (!rawDate) return new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
    return new Date(rawDate).toLocaleString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  return (
    <div className="p-6 space-y-6 max-w-7xl mx-auto">
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-foreground flex items-center gap-2">
          <History className="h-6 w-6 text-primary" />
          Generated Letters History
        </h1>
        <p className="text-sm text-muted-foreground">
          View past generated employee documents, offer letters, and official statements.
        </p>
      </div>

      <Card className="border border-border/40 shadow-sm">
        <CardContent className="p-0">
          {isLoading ? (
            <div className="p-8 text-center text-muted-foreground">Loading history...</div>
          ) : error ? (
            <div className="p-8 text-center text-red-500">Failed to load letter history.</div>
          ) : letters.length === 0 ? (
            <div className="py-12">
              <EmptyState title="No History" message="No letters or certificates have been generated yet." />
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Template</TableHead>
                  <TableHead>Employee</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead>Generated Date</TableHead>
                  <TableHead className="text-right">Action</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {letters.map((letItem: any) => (
                  <TableRow key={letItem.id} className="hover:bg-muted/40 transition-colors">
                    <TableCell className="font-semibold text-foreground">
                      {letItem.template_name || letItem.template?.name || `Template #${letItem.template}`}
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-1.5 text-sm text-foreground">
                        <User className="h-3.5 w-3.5 text-muted-foreground" />
                        {letItem.employee_name || letItem.employee?.name || `Employee #${letItem.employee}`}
                      </div>
                    </TableCell>
                    <TableCell className="text-sm text-muted-foreground">
                      {letItem.generated_by_name || letItem.generated_by?.name || "HR Admin"}
                    </TableCell>
                    <TableCell className="text-sm text-muted-foreground font-mono text-xs">
                      {getDateDisplay(letItem)}
                    </TableCell>
                    <TableCell className="text-right">
                      <Button variant="outline" size="sm" className="gap-1.5" onClick={() => setSelectedLetter(letItem)}>
                        <Eye className="h-3.5 w-3.5" />
                        View & PDF
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      <Dialog open={!!selectedLetter} onOpenChange={() => setSelectedLetter(null)}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto p-4 sm:p-6">
          <DialogHeader>
            <DialogTitle className="text-lg font-bold flex items-center gap-2">
              <FileText className="h-5 w-5 text-emerald-600" />
              MNC Standard Document Preview & PDF Download
            </DialogTitle>
          </DialogHeader>
          {selectedLetter && (
            <div className="py-2">
              <MncLetterDocument
                templateName={selectedLetter.template_name || selectedLetter.template?.name || "Standard HR Document"}
                employeeName={selectedLetter.employee_name || selectedLetter.employee?.name || "Employee"}
                employeeCode={`VTL-EMP-${selectedLetter.employee}`}
                date={getDateDisplay(selectedLetter)}
                refNumber={`VTL/HR/${new Date().getFullYear()}/DOC-${selectedLetter.id}`}
                content={selectedLetter.generated_content}
                onClose={() => setSelectedLetter(null)}
              />
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
