# Generated by Django 5.2.5 on 2026-08-05 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0015_alter_appnotification_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("trainer_name", models.CharField(max_length=150)),
                (
                    "mode",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("duration_hours", models.FloatField()),
                (
                    "target_department",
                    models.CharField(
                        blank=True, help_text="Blank = all departments", max_length=100
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_training_programs",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Program",
                "verbose_name_plural": "Training Programs",
                "db_table": "training_trainingprogram",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="TrainingEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attended", models.BooleanField(default=False)),
                (
                    "feedback_rating",
                    models.IntegerField(blank=True, help_text="Rating 1-5", null=True),
                ),
                ("feedback_comment", models.TextField(blank=True)),
                ("enrolled_on", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_enrollments",
                        to="users.employee",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="training.trainingprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Enrollment",
                "verbose_name_plural": "Training Enrollments",
                "db_table": "training_trainingenrollment",
                "unique_together": {("program", "employee")},
            },
        ),
    ]
