# Generated by Django 5.2.5 on 2026-08-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingprogram",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
