# Generated by Django 6.0.4 on 2026-04-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('check_in_lat', models.FloatField(blank=True, null=True)),
                ('check_in_lng', models.FloatField(blank=True, null=True)),
                ('break_minutes', models.IntegerField(default=0)),
                ('total_hours', models.FloatField(default=0)),
                ('overtime_hours', models.FloatField(default=0)),
                ('status', models.CharField(default='present', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BreakLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.DateTimeField()),
                ('break_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
