# Generated by Django 5.2.5 on 2026-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
