# Generated by Django 5.2.5 on 2026-08-13 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_alter_attendancelog_date"),
        ("updates", "0009_alter_task_status"),
        ("users", "0016_employee_aadhaar_number_employee_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskInterruptionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interruption_type",
                    models.CharField(
                        choices=[("break", "Break"), ("checkout", "Check‑Out")],
                        max_length=10,
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField()),
                ("task_status_at_time", models.CharField(max_length=20)),
                ("deadline_at_time", models.DateTimeField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_interruption_logs",
                        to="users.employee",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interruption_logs",
                        to="updates.task",
                    ),
                ),
            ],
        ),
    ]
