# Generated by Django 5.2.5 on 2026-05-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_half_day_and_decimal_balances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual'), ('sick', 'Sick'), ('earned', 'Earned'), ('exam', 'Exam'), ('college', 'College'), ('other', 'Other')], max_length=20),
        ),
    ]
