# Generated by Django 5.2.5 on 2026-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(),
        ),
    ]
