# Generated by Django 5.2.5 on 2026-08-05 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0015_alter_appnotification_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppraisalCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("closed", "Closed")],
                        default="active",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Appraisal Cycle",
                "verbose_name_plural": "Appraisal Cycles",
                "db_table": "performance_appraisalcycle",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("target_metric", models.TextField()),
                (
                    "weightage",
                    models.IntegerField(help_text="Percentage weightage (0-100)"),
                ),
                (
                    "self_rating",
                    models.IntegerField(blank=True, help_text="Rating 1-5", null=True),
                ),
                ("self_comment", models.TextField(blank=True)),
                (
                    "manager_rating",
                    models.IntegerField(blank=True, help_text="Rating 1-5", null=True),
                ),
                ("manager_comment", models.TextField(blank=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="performance.appraisalcycle",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_goals",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goal",
                "verbose_name_plural": "Goals",
                "db_table": "performance_goal",
            },
        ),
        migrations.CreateModel(
            name="Appraisal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_rating", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("self_assessment_pending", "Self Assessment Pending"),
                            ("manager_review_pending", "Manager Review Pending"),
                            ("completed", "Completed"),
                        ],
                        default="self_assessment_pending",
                        max_length=30,
                    ),
                ),
                ("finalized_on", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_appraisals",
                        to="users.employee",
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finalized_appraisals",
                        to="users.employee",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appraisals",
                        to="performance.appraisalcycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appraisal",
                "verbose_name_plural": "Appraisals",
                "db_table": "performance_appraisal",
                "unique_together": {("cycle", "employee")},
            },
        ),
    ]
