# Generated by Django 5.2.5 on 2026-08-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0001_initial"),
        ("users", "0016_employee_aadhaar_number_employee_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appraisal",
            name="employee_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appraisal",
            name="initiative_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appraisal",
            name="initiative_rating",
            field=models.IntegerField(
                blank=True,
                help_text="Rating 1-5 for problem solving and ownership",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appraisal",
            name="manager_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appraisal",
            name="productivity_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appraisal",
            name="productivity_rating",
            field=models.IntegerField(
                blank=True,
                help_text="Rating 1-5 for task speed and deadline compliance",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appraisal",
            name="punctuality_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appraisal",
            name="punctuality_rating",
            field=models.IntegerField(
                blank=True,
                help_text="Rating 1-5 for punctuality, attendance, and late arrival record",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appraisal",
            name="quality_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appraisal",
            name="quality_rating",
            field=models.IntegerField(
                blank=True,
                help_text="Rating 1-5 for work quality and accuracy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appraisal",
            name="teamwork_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appraisal",
            name="teamwork_rating",
            field=models.IntegerField(
                blank=True,
                help_text="Rating 1-5 for communication and team collaboration",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appraisalcycle",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="appraisalcycle",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appraisalcycle",
            name="target_department",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="appraisalcycle",
            name="target_employees",
            field=models.ManyToManyField(
                blank=True,
                related_name="targeted_appraisal_cycles",
                to="users.employee",
            ),
        ),
        migrations.AddField(
            model_name="appraisalcycle",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("all", "All Employees"),
                    ("department", "Specific Department"),
                    ("employees", "Specific Employees"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
