# Generated by Django 5.2.5 on 2026-08-05 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0015_alter_appnotification_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="HRTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("General", "General"),
                            ("Payroll", "Payroll"),
                            ("IT", "IT"),
                            ("Facilities", "Facilities"),
                            ("Grievance", "Grievance"),
                        ],
                        default="General",
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="hr_tickets/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("resolved_on", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_hr_tickets",
                        to="users.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_tickets",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "HR Ticket",
                "verbose_name_plural": "HR Tickets",
                "db_table": "ess_hrticket",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="ProfileChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("requested_value", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_on", models.DateTimeField(auto_now_add=True)),
                ("reviewed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_change_requests",
                        to="users.employee",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_profile_changes",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Change Request",
                "verbose_name_plural": "Profile Change Requests",
                "db_table": "ess_profilechangerequest",
                "ordering": ["-requested_on"],
            },
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_comments",
                        to="users.employee",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="ess.hrticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Comment",
                "verbose_name_plural": "Ticket Comments",
                "db_table": "ess_ticketcomment",
                "ordering": ["created_on"],
            },
        ),
    ]
