# Generated by Django 5.2.5 on 2026-08-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ess", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrticket",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="hrticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("Payroll", "Payroll"),
                    ("Attendance", "Attendance / Leaves"),
                    ("IT", "IT Support"),
                    ("Policy", "Policy / HR"),
                    ("Facilities", "Facilities"),
                    ("Grievance", "Grievance"),
                    ("Other", "Other"),
                    ("payroll", "Payroll"),
                    ("attendance", "Attendance"),
                    ("it_support", "IT Support"),
                    ("policy", "Policy"),
                    ("other", "Other"),
                ],
                default="General",
                max_length=50,
            ),
        ),
    ]
