# Generated by Django 5.2.5 on 2026-08-05 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0015_alter_appnotification_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "body_template",
                    models.TextField(
                        help_text="HTML or plain text template using {{employee.field_name}} placeholders"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_letter_templates",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Letter Template",
                "verbose_name_plural": "Letter Templates",
                "db_table": "documents_lettertemplate",
            },
        ),
        migrations.CreateModel(
            name="GeneratedLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_content", models.TextField()),
                ("generated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="generated_letters/"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_letters",
                        to="users.employee",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="letters_generated_by_user",
                        to="users.employee",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_letters",
                        to="documents.lettertemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Letter",
                "verbose_name_plural": "Generated Letters",
                "db_table": "documents_generatedletter",
                "ordering": ["-generated_on"],
            },
        ),
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HR Policy", "HR Policy"),
                            ("IT Policy", "IT Policy"),
                            ("Code of Conduct", "Code of Conduct"),
                            ("Other", "Other"),
                        ],
                        default="HR Policy",
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="policy_documents/")),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("published_on", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_policies",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Document",
                "verbose_name_plural": "Policy Documents",
                "db_table": "documents_policydocument",
                "ordering": ["-published_on"],
            },
        ),
    ]
