# Generated by Django 5.2.5 on 2026-08-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policydocument",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="policydocument",
            name="category",
            field=models.CharField(
                blank=True,
                default="General",
                help_text="e.g. HR Policy, IT Policy, Code of Conduct, Benefits, Compliance",
                max_length=100,
            ),
        ),
    ]
