# Generated by Django 5.2.5 on 2026-08-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_policy_free_text_category_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lettertemplate",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Letter Template",
                "verbose_name_plural": "Letter Templates",
            },
        ),
        migrations.AddField(
            model_name="lettertemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="lettertemplate",
            name="subject_template",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Email/letter subject line with {{employee.field}} placeholders",
                max_length=300,
            ),
        ),
    ]
