# Generated by Django 5.2.5 on 2026-08-05 06:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0015_alter_appnotification_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("finalized", "Finalized"),
                            ("locked", "Locked"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("generated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_payroll_runs",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Run",
                "verbose_name_plural": "Payroll Runs",
                "db_table": "payroll_payrollrun",
                "unique_together": {("month", "year")},
            },
        ),
        migrations.CreateModel(
            name="SalaryComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "component_type",
                    models.CharField(
                        choices=[("earning", "Earning"), ("deduction", "Deduction")],
                        max_length=10,
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("percentage", "Percentage")],
                        max_length=10,
                    ),
                ),
                (
                    "percentage_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="percentage_components",
                        to="payroll.salarycomponent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Component",
                "verbose_name_plural": "Salary Components",
                "db_table": "payroll_salarycomponent",
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField()),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_structure",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Structure",
                "verbose_name_plural": "Salary Structures",
                "db_table": "payroll_salarystructure",
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gross_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "lop_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                ("generated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="users.employee",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="payroll.payrollrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payslip",
                "verbose_name_plural": "Payslips",
                "db_table": "payroll_payslip",
                "unique_together": {("payroll_run", "employee")},
            },
        ),
        migrations.CreateModel(
            name="SalaryStructureComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structure_components",
                        to="payroll.salarycomponent",
                    ),
                ),
                (
                    "salary_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="payroll.salarystructure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Structure Component",
                "verbose_name_plural": "Salary Structure Components",
                "db_table": "payroll_salarystructurecomponent",
                "unique_together": {("salary_structure", "component")},
            },
        ),
    ]
