# Generated by Django 5.2.5 on 2026-08-13 05:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
        ("users", "0016_employee_aadhaar_number_employee_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyPayrollPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "BASIC_PERCENT",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("40.00"), max_digits=5
                    ),
                ),
                (
                    "HRA_PERCENT_METRO",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("20.00"), max_digits=5
                    ),
                ),
                (
                    "HRA_PERCENT_NON_METRO",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("15.00"), max_digits=5
                    ),
                ),
                (
                    "lop_calculation_basis",
                    models.CharField(
                        choices=[
                            ("calendar", "Calendar Days"),
                            ("working", "Working Days"),
                        ],
                        default="working",
                        max_length=10,
                    ),
                ),
                ("rounding_rule", models.CharField(default="nearest", max_length=20)),
            ],
            options={
                "verbose_name": "Company Payroll Policy",
                "verbose_name_plural": "Company Payroll Policies",
                "db_table": "payroll_companypolicy",
            },
        ),
        migrations.CreateModel(
            name="StatutoryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pf_rate_employee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("12.00"), max_digits=5
                    ),
                ),
                (
                    "pf_rate_employer",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("12.00"), max_digits=5
                    ),
                ),
                (
                    "pf_ceiling",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("150000"), max_digits=10
                    ),
                ),
                (
                    "esi_rate_employee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.75"), max_digits=5
                    ),
                ),
                (
                    "esi_rate_employer",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("3.25"), max_digits=5
                    ),
                ),
                ("professional_tax_slabs", models.JSONField(default=dict)),
                (
                    "tds_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=5
                    ),
                ),
            ],
            options={
                "verbose_name": "Statutory Config",
                "verbose_name_plural": "Statutory Configs",
                "db_table": "payroll_statutoryconfig",
            },
        ),
        migrations.AddField(
            model_name="payslip",
            name="employer_esi",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payslip",
            name="employer_gratuity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payslip",
            name="employer_pf",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payslip",
            name="lop_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payslip",
            name="net_pay_in_words",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="payslip",
            name="pdf_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payslip",
            name="ytd_gross",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payslip",
            name="ytd_pf",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payslip",
            name="ytd_prof_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payslip",
            name="ytd_tds",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="PayrollRevisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("change_reason", models.CharField(blank=True, max_length=255)),
                ("before_snapshot", models.JSONField()),
                ("after_snapshot", models.JSONField()),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_logs",
                        to="payroll.payslip",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Revision Log",
                "verbose_name_plural": "Payroll Revision Logs",
                "db_table": "payroll_revisionlog",
            },
        ),
        migrations.CreateModel(
            name="AttendanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("total_days_in_month", models.PositiveSmallIntegerField()),
                ("present_days", models.PositiveSmallIntegerField()),
                ("paid_leave_days", models.PositiveSmallIntegerField()),
                ("unpaid_leave_days", models.PositiveSmallIntegerField()),
                ("holidays", models.PositiveSmallIntegerField()),
                ("weekly_offs", models.PositiveSmallIntegerField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_summaries",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_attendance_summary",
                "unique_together": {("employee", "month", "year")},
            },
        ),
    ]
