# Generated by Django 5.2.5 on 2026-08-13 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_companypayrollpolicy_statutoryconfig_and_more"),
        ("users", "0016_employee_aadhaar_number_employee_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("monthly_emi", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tenure_months", models.PositiveIntegerField()),
                ("disbursed_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("CLOSED", "Closed")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "remaining_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Loan",
                "verbose_name_plural": "Employee Loans",
                "db_table": "payroll_employeeloan",
            },
        ),
        migrations.CreateModel(
            name="PayrollRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("old_values", models.JSONField()),
                ("new_values", models.JSONField()),
                ("revised_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="payroll.payrollrun",
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="payroll.payslip",
                    ),
                ),
                (
                    "revised_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Revision",
                "verbose_name_plural": "Payroll Revisions",
                "db_table": "payroll_revision",
            },
        ),
        migrations.CreateModel(
            name="ProfessionalTaxSlab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=50)),
                (
                    "min_gross_salary",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "max_gross_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "monthly_pt_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "verbose_name": "Professional Tax Slab",
                "verbose_name_plural": "Professional Tax Slabs",
                "db_table": "payroll_professionaltaxslab",
                "unique_together": {("state", "min_gross_salary", "max_gross_salary")},
            },
        ),
        migrations.CreateModel(
            name="ReimbursementClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True, null=True, upload_to="reimbursements/"
                    ),
                ),
                ("claim_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PAID", "Paid"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_claims",
                        to="users.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reimbursements",
                        to="users.employee",
                    ),
                ),
                (
                    "paid_in_payroll_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payroll.payrollrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reimbursement Claim",
                "verbose_name_plural": "Reimbursement Claims",
                "db_table": "payroll_reimbursementclaim",
            },
        ),
        migrations.CreateModel(
            name="LoanRepaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_month", models.CharField(max_length=7)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("paid", models.BooleanField(default=False)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayment_schedule",
                        to="payroll.employeeloan",
                    ),
                ),
                (
                    "paid_in_payroll_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payroll.payrollrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Repayment Schedule",
                "verbose_name_plural": "Loan Repayment Schedules",
                "db_table": "payroll_loanrepaymentschedule",
                "unique_together": {("loan", "due_month")},
            },
        ),
    ]
