# Generated by Django 5.2.5 on 2026-08-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr', 'HR'), ('sales', 'Sales'), ('admin', 'Admin')], max_length=20)),
                ('module', models.CharField(choices=[('users', 'Employee Management'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('recruitment', 'Recruitment'), ('performance', 'Performance'), ('ess', 'Employee Self-Service'), ('tasks', 'Tasks'), ('documents', 'Documents'), ('training', 'Training'), ('exit_mgmt', 'Exit Management'), ('reports', 'Reports & Analytics'), ('sysadmin', 'System Administration')], max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Role module permission',
                'verbose_name_plural': 'Role module permissions',
                'ordering': ['role', 'module'],
                'unique_together': {('role', 'module')},
            },
        ),
    ]
