# Generated by Django 5.2.5 on 2026-08-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sysadmin", "0002_role_auditlog_notification_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolemodulepermission",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("intern", "Intern"),
                    ("manager", "Manager"),
                    ("hr", "HR"),
                    ("sales", "Sales"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
