# Generated by Django 6.0.4 on 2026-05-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_alter_dailyupdate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyupdate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
