# Generated by Django 5.2.5 on 2026-05-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0004_alter_dailyupdate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyupdate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
