# Generated by Django 5.2.5 on 2026-05-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0006_dailyupdate_report_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyupdate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
