# Generated by Django 5.2.5 on 2026-08-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("updates", "0008_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("reviewed", "Reviewed"),
                    ("reopened", "Revision Requested"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
