# Generated by Django 5.2.5 on 2026-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_appnotification_created_at_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
