# Generated by Django 5.2.5 on 2026-08-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_appnotification_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="aadhaar_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_account_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="designation",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="grade",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="ifsc_code",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="employee",
            name="pan_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="employee",
            name="salary",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("intern", "Intern"),
                    ("manager", "Manager"),
                    ("hr", "HR"),
                    ("sales", "Sales"),
                    ("admin", "Admin"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
